### ISSUE TITLE
'java.lang.IllegalStateException' message after project execution

### ISSUE THREAD

**Issue by amazzetto** [tomatsu/squawk#2]
Hello,

we are able to make a simple "Hello World" test project and execute it.
Our test project does not have an infinite loop, but it finishes and exits after showing the message "Hello World".

We are experiencing a` java.lang.IllegalStateException` message after our program was executed.
We tried placing a `System.exit(0);` at the end of our project, but without success.
Furthermore, we tried changing some values of the `build.properties` file based on comments and common sense, with the same result.

Is this a bug?
Does the `java.lang.IllegalStateException` message is somehow linked to the squawk engine or a specific entry in the `build.properties` file?

Thank you,

Alberto

**Comment by tomatsu** [comment]
Yes, that was a bug.  [1243036](https://github.com/tomatsu/squawk/commit/1243036a2b51d1bbb5b3c450e3b86b0fb29cf4d8) should fix the problem.

**Comment by amazzetto** [comment]
Thank you, bug fixed.
